#!/bin/bash

# Environment variables for hostnames (fill these in with your actual hostnames)
WORK_LAPTOP_HOSTNAME="ANW3Q4F9WYJ"
HOME_LAPTOP_HOSTNAME="Sants-MacBook-Pro.local"

# Function to detect the current laptop
detect_laptop() {
  if [[ $(hostname) == "$WORK_LAPTOP_HOSTNAME" ]]; then
    echo "work_laptop"
  elif [[ $(hostname) == "$HOME_LAPTOP_HOSTNAME" ]]; then
    echo "home_laptop"
  else
    echo "unknown_laptop"
  fi
}

# Function to detect the current monitor setup
detect_monitor() {
  if [[ $(system_profiler SPDisplaysDataType | grep "Resolution: 3440 x 1440") ]]; then
    echo "work_monitor"
  elif [[ $(system_profiler SPDisplaysDataType | grep "Resolution: 2560 x 2880") ]]; then
    echo "home_monitor"
  else
    echo "unknown_monitor"
  fi
}

# Get the detected laptop and monitor setup
LAPTOP=$(detect_laptop)
MONITOR=$(detect_monitor)

# Set padding values based on the detected laptop and monitor setup
case "$LAPTOP-$MONITOR" in
"work_laptop-work_monitor")
  TOP_PADDING=20
  BOTTOM_PADDING=200
  ;;
"work_laptop-unknown_monitor")
  TOP_PADDING=20
  BOTTOM_PADDING=200
  ;;
"work_laptop-home_monitor")
  TOP_PADDING=250
  BOTTOM_PADDING=300
  ;;
"home_laptop-home_monitor")
  TOP_PADDING=200
  BOTTOM_PADDING=300
  ;;
*)
  # Default settings if the combination is not recognized
  TOP_PADDING=20
  BOTTOM_PADDING=20
  ;;
esac

# Global settings
LR_PADDING=20
WINDOW_GAP=20

# Default layout (can be bsp, stack or float)
yabai -m config layout bsp

# Apply settings
yabai -m config top_padding $TOP_PADDING
yabai -m config bottom_padding $BOTTOM_PADDING
yabai -m config left_padding $LR_PADDING
yabai -m config right_padding $LR_PADDING
yabai -m config window_gap $WINDOW_GAP

# on or off (default: off)
yabai -m config auto_balance on

# -- mouse settings --
# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# -- Space settings --

SPACE_TB_PADDING=20
SPACE_TB_PADDING=20

yabai -m config --space 4 top_padding $SPACE_TB_PADDING
yabai -m config --space 5 top_padding $SPACE_TB_PADDING
yabai -m config --space 6 top_padding $SPACE_TB_PADDING

yabai -m config --space 4 bottom_padding $SPACE_TB_PADDING
yabai -m config --space 5 bottom_padding $SPACE_TB_PADDING
yabai -m config --space 6 bottom_padding $SPACE_TB_PADDING

# -- window rules --
# float non resizable windows (e.g. settings)
yabai -m signal --add event=window_created action="sh -c '\
  WINDOW_ID=\$YABAI_WINDOW_ID; \
  CAN_RESIZE=\$(yabai -m query --windows --window \$WINDOW_ID | jq -r \".[\\\"can-resize\\\"]\"); \
  if [ \"\$CAN_RESIZE\" = \"false\" ]; then \
    yabai -m window \$WINDOW_ID --toggle float; \
  fi'"

# disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Skitch$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Cypress$" manage=off
yabai -m rule --add app="^zoom\.us$" manage=off
yabai -m rule --add title="^Zoom Meeting$" manage=off
yabai -m rule --add app="^GitKraken$" manage=off
yabai -m rule --add app="^Webex$" manage=off
yabai -m rule --add app="^Simulator$" manage=off
